Fix loader error

diff --git a/recipes/xilinx-runtime/conda.patch b/recipes/xilinx-runtime/conda.patch
--- a/recipes/xilinx-runtime/conda.patch
+++ b/recipes/xilinx-runtime/conda.patch
@@ -330,6 +330,38 @@ diff -Naur XRT-202210.2.13.466/src/runtime_src/tools/scripts/CMakeLists.txt work
  install (PROGRAMS ${XRT_LOADER_SCRIPTS} DESTINATION ${XRT_INSTALL_UNWRAPPED_DIR})
 -install (FILES ${XRT_SETUP_SCRIPTS} DESTINATION ${XRT_INSTALL_DIR})
 +#install (FILES ${XRT_SETUP_SCRIPTS} DESTINATION ${XRT_INSTALL_DIR})
+diff -Naur XRT-202210.2.13.466/src/runtime_src/tools/scripts/loader work/src/runtime_src/tools/scripts/loader
+--- XRT-202210.2.13.466/src/runtime_src/tools/scripts/loader	2022-04-14 12:29:02.000000000 -0700
++++ work/src/runtime_src/tools/scripts/loader	2022-06-21 09:49:45.882496746 -0700
+@@ -42,20 +42,20 @@
+ fi
+ 
+ # -- Find the setup script and configure environment
+-XRT_SETUP_SCRIPT="`dirname \"$0\"`/../../setup.sh"
++#XRT_SETUP_SCRIPT="`dirname \"$0\"`/../../setup.sh"
+ 
+-if [ ! -f "$XRT_SETUP_SCRIPT" ]; then
+-  echo "ERROR: Could not find XRT setup script."
+-  echo "ERROR: ${XRT_SETUP_SCRIPT} does not exist"
+-  exit 1
+-fi
++#if [ ! -f "$XRT_SETUP_SCRIPT" ]; then
++#  echo "ERROR: Could not find XRT setup script."
++#  echo "ERROR: ${XRT_SETUP_SCRIPT} does not exist"
++#  exit 1
++#fi
+ 
+-. "${XRT_SETUP_SCRIPT}" > /dev/null
++#. "${XRT_SETUP_SCRIPT}" > /dev/null
+ 
+ # XRT uses system librairies whereas Vitis and Vivado ship there own.
+ # when XRT tools are invoked from Vitis/Vivado the LD_LIBRARY_PATH will be set to use libraries shipped with Vitis/vivado
+ # so we reset the LD_LIBRARY_PATH to make XRT tool select the correct libraries.
+-LD_LIBRARY_PATH=$XILINX_XRT/lib:$(echo $LD_LIBRARY_PATH | tr ':' '\n' | grep -E -v "/(Vitis|Vivado).*/(lnx|lin)" | tr '\n' ':')
++#LD_LIBRARY_PATH=$XILINX_XRT/lib:$(echo $LD_LIBRARY_PATH | tr ':' '\n' | grep -E -v "/(Vitis|Vivado).*/(lnx|lin)" | tr '\n' ':')
+ 
+ # -- Execute the wrapped program
+ "${XRT_PROG_UNWRAPPED}" "${XRT_LOADER_ARGS[@]}"
 diff -Naur XRT-202210.2.13.466/src/runtime_src/xdp/CMakeLists.txt work/src/runtime_src/xdp/CMakeLists.txt
 --- XRT-202210.2.13.466/src/runtime_src/xdp/CMakeLists.txt	2022-04-14 12:29:02.000000000 -0700
 +++ work/src/runtime_src/xdp/CMakeLists.txt	2022-06-21 00:48:13.628886405 -0700
