commit

diff --git a/recipes/git-bash/01-devices.post.patch b/recipes/git-bash/01-devices.post.patch
--- a/recipes/git-bash/01-devices.post.patch
+++ b/recipes/git-bash/01-devices.post.patch
@@ -1,38 +1,77 @@
 --- a/01-devices.post
 +++ b/01-devices.post
-@@ -44,7 +44,7 @@ maybe_create_devs ()
+@@ -17,7 +17,8 @@ maybe_create_devs ()
+   fi
+ 
    # Create it if necessary
+-  mkdir -m 755 "${DEVDIR}" 2> /dev/null
++  mkdir -p "${DEVDIR}" 2>/dev/null || true
++  chmod 755 "${DEVDIR}"
+   if [ ! -e "${DEVDIR}" ]
+   then
+     echo
+@@ -38,22 +39,20 @@ maybe_create_devs ()
+       echo "${DEVDIR}/shm is existant but not a directory."
+       echo "POSIX semaphores and POSIX shared memory will not work"
+       echo
++      exit 1
+     fi
+   fi
+ 
+   # Create it if necessary
++  mkdir -p "${DEVDIR}/shm" 2>/dev/null || true
++  chmod 1777 "${DEVDIR}/shm"
    if [ ! -e "${DEVDIR}/shm" ]
    then
 -    mkdir -m 1777 "${DEVDIR}/shm"
-+    mkdir -m 1777 "${DEVDIR}/shm" 2> /dev/null
-     if [ ! -e "${DEVDIR}/shm" ]
-     then
-       echo
-@@ -53,7 +53,7 @@ maybe_create_devs ()
-       echo
-     fi
-   else
+-    if [ ! -e "${DEVDIR}/shm" ]
+-    then
+-      echo
+-      echo "Creating ${DEVDIR}/shm directory failed."
+-      echo "POSIX semaphores and POSIX shared memory will not work"
+-      echo
+-    fi
+-  else
 -    chmod 1777 "${DEVDIR}/shm"
-+    chmod 1777 "${DEVDIR}/shm" 2> /dev/null
++    echo
++    echo "Creating ${DEVDIR}/shm directory failed."
++    echo "POSIX semaphores and POSIX shared memory will not work"
++    echo
++    exit 1
    fi
  
    # Check for ${DEVDIR}/mqueue directory (for POSIX message queues)
-@@ -73,7 +73,7 @@ maybe_create_devs ()
+@@ -67,24 +66,22 @@ maybe_create_devs ()
+       echo "${DEVDIR}/mqueue is existant but not a directory."
+       echo "POSIX message queues will not work"
+       echo
++      exit 1
+     fi
+   fi
+ 
    # Create it if necessary
++  mkdir -p "${DEVDIR}/mqueue" 2>/dev/null || true
++  chmod 1777 "${DEVDIR}/mqueue"
    if [ ! -e "${DEVDIR}/mqueue" ]
    then
 -    mkdir -m 1777 "${DEVDIR}/mqueue"
-+    mkdir -m 1777 "${DEVDIR}/mqueue" 2> /dev/null
-     if [ ! -e "${DEVDIR}/mqueue" ]
-     then
-       echo
-@@ -82,7 +82,7 @@ maybe_create_devs ()
-       echo
-     fi
-   else
+-    if [ ! -e "${DEVDIR}/mqueue" ]
+-    then
+-      echo
+-      echo "Creating ${DEVDIR}/mqueue directory failed."
+-      echo "POSIX message queues will not work"
+-      echo
+-    fi
+-  else
 -    chmod 1777 "${DEVDIR}/mqueue"
-+    chmod 1777 "${DEVDIR}/mqueue" 2> /dev/null
++    echo
++    echo "Creating ${DEVDIR}/mqueue directory failed."
++    echo "POSIX message queues will not work"
++    echo
++    exit 1
    fi
-   
+-  
++
    # Install /dev/fd, /dev/std{in,out,err}.  The bash builtin test was compiled
+   # to assume these exist, so use /bin/test to really check.
+   /usr/bin/test -h /dev/stdin  || ln -sf /proc/self/fd/0 /dev/stdin
