Travis: Fast finish old PR builds
Using Travis CI's API and information about the current build, this
script checks to see if the current PR build is the most recent one. It
does this by comparing the current PR build's build number to other
build numbers of builds for this PR. If it is not the most recent build
for the PR, then the build is failed stopping it from proceeding
further. However, if it is the most recent build number or if it is not
a PR (e.g. a build on a user's fork), then the build proceeds without
issues.

[skip lint]
[skip appveyor]

diff --git a/.CI/build_all b/.CI/build_all
--- a/.CI/build_all
+++ b/.CI/build_all
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
 
+# Fast finish the PR.
+echo ""
+echo "Checking to see if this build is outdated."
+.CI/travis_fast_finish.py || { echo "Failing outdated build to end it."; exit 1; }
+
 # Set the numpy variable. This isn't used, but conda-build complains if we haven't set it already.
 export CONDA_NPY=19
 
