Implement output validation tests in recipe.yaml
Add tests for rust-sasa output validation

diff --git a/recipes/rust-sasa/recipe.yaml b/recipes/rust-sasa/recipe.yaml
--- a/recipes/rust-sasa/recipe.yaml
+++ b/recipes/rust-sasa/recipe.yaml
@@ -33,6 +33,25 @@ tests:
   - script:
       - rust-sasa --help
       - rust-sasa --version
+      - |
+        set -exo pipefail
+
+        rust-sasa ${PREFIX}/share/pdbs/example.cif out.json
+
+        if [[ ! -f out.json ]]; then
+          echo "File out.json does not exist"
+          exit 1
+        fi
+
+        output=$(cat out.json)
+        
+        expected='"value":222.80806,"name":"MET","is_polar":false'
+        if ! echo "$output" | grep -q "$expected"; then
+          echo "Expected string '$expected' not found in output"
+          exit 1
+        fi
+        
+        echo "Test passed!"
 
 about:
   homepage: "https://crates.io/crates/rust-sasa"
